import jQuery from 'jquery';
window.$ = window.jQuery = jQuery;
// require('bootstrap');
require( 'datatables.net-dt');
require('jsgrid');
require('select2');
import PerfectScrollbar from 'perfect-scrollbar';
window.PerfectScrollbar = PerfectScrollbar;
require('./bootstrap');
require('./custom'); 